### ISSUE TITLE
StartTime is 7 days in the past

### ISSUE THREAD

**Issue by MooreDerek** [census-instrumentation/opencensus-web#165]
Using version 0.0.5
Firefox: 68.0.1

Following the documentation to run the `examples/initial_load` , running locally on Mac OSx. Running the same page, with output to `zipkin`

### What did you expect to see?
Starttime for local time - currently 2019-08-22

### What did you see instead?

startTime | 2019-08-14T07:13:34.214000000Z

### Additional context
```
config.yaml 
receivers:
  opencensus:
    address: "127.0.0.1:55678"
    cors_allowed_origins:
      - http://localhost:*
exporters:
  zipkin:
    service_name: "opencensus"
    endpoint: "http://127.0.0.1:9411/api/v2/spans"
```
